### ISSUE TITLE
Release 1.1.0 breaks the asset compilation

### ISSUE THREAD

**Issue by Tolsto** [mvz/non-digest-assets#34]
Release 1.1.0 breaks the asset compilation for me. The problem occurs with the ckeditor gem and the file `ckeditor/samples/toolbarconfigurator/lib/codemirror/LICENSE`. This file does not seem to get a digest version in which case `full_digest_path` equals `full_non_digest_path`. Since the `copy_file` method removes the `to` file it also removes the source file resulting in `Errno::ENOENT Exception: No such file or directory @ rb_sysopen`

**Comment by mvz** [comment]
Thanks, @Tolsto, I'll look into it.
