### ISSUE TITLE
Not workin within engine

### ISSUE THREAD

**Issue by Sega100500** [mvz/non-digest-assets#74]
https://github.com/rails/sprockets-rails/issues/507

**Comment by mvz** [comment]
@Sega100500 how do you think the non-digest-assets gem should help here? It looks like things are already not working for you with plain sporckets-rails.

**Comment by Sega100500** [comment]
in Issue:
background: #5c9ccc url(/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png) 50% 50% repeat-x;

style use non-digest asset '/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png'

**Comment by mvz** [comment]
That url is always rewritten by sprockets and non-digest-assets does not change that.

**Comment by Sega100500** [comment]
@mvz 
I already [find the bug in `sprockets_rails` and offers the patch](https://github.com/rails/sprockets-rails/issues/507#issuecomment-1172928861)

Thanks. I'm sorry I contacted you at the wrong address.
